## Numpy의 indexing

In [1]:
# 우선 실행해주세요
import numpy as np

> 문제 1번, 문제 2번, 문제 3번은 table-1을 참고하여 풀어주세요!

#### table-1) 학생들의 중간고사, 기말고사 성적표

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

## 문제 1. np.concatenate 후의 shape 예측하기
* 위의 중간고사, 기말고사 성적표 데이터를 axis`1`을 기준으로 concatenate 했을 때의 shape를 구해주세요

In [2]:
# 우선 실행해주세요
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

In [3]:
answer1 = (6,10)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [4]:
assert 'answer1' in globals(), "결과를 answer1이라는 변수에 담아주세요!, answer1의 값을 보고 평가합니다."

if (answer1 == np.concatenate((middle_scores, final_scores), axis=1).shape):
    print("정답입니다!!!!")
    print("concatenate한 결과가 무엇을 의미하는지 잘 생각해보세요!")
else:
    raise ValueError("shape가 맞지 않습니다. 다시 생각해보세요!")

정답입니다!!!!
concatenate한 결과가 무엇을 의미하는지 잘 생각해보세요!

## 문제 2. np.stack 후의 shape 예측하기(1)
* 위의 중간고사, 기말고사 성적표 데이터를 axis`1`을 기준으로 stack 했을 때의 shape를 구해주세요

In [5]:
# 우선 실행해주세요
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

In [6]:
answer2 = (6,2,5)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [7]:
assert 'answer2' in globals(), "결과를 answer2라는 변수에 담아주세요!, answer2의 값을 보고 평가합니다."

if (answer2 == np.stack((middle_scores, final_scores), axis=1).shape):
    print("정답입니다!!!!")
    print("stack한 결과가 무엇을 의미하는지 잘 생각해보세요!")
else:
    raise ValueError("shape가 맞지 않습니다. 다시 생각해보세요!")

정답입니다!!!!
stack한 결과가 무엇을 의미하는지 잘 생각해보세요!

## 문제 3. np.stack 후의 shape 예측하기(2)
* 위의 중간고사, 기말고사 성적표 데이터를 axis`2`을 기준으로 stack 했을 때의 shape를 구해주세요

In [8]:
# 우선 실행해주세요
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

In [9]:
answer3 = (6,5,2)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [10]:
assert 'answer3' in globals(), "결과를 answer3이라는 변수에 담아주세요!, answer3의 값을 보고 평가합니다."

if (answer3 == np.stack((middle_scores, final_scores), axis=2).shape):
    print("정답입니다!!!!")
    print("stack한 결과가 무엇을 의미하는지 잘 생각해보세요!")
else:
    raise ValueError("shape가 맞지 않습니다. 다시 생각해보세요!")

정답입니다!!!!
stack한 결과가 무엇을 의미하는지 잘 생각해보세요!

## 문제 4. 행렬의 shape 변경하기(1)
* 아래의 행렬, arr가 행이 5개, 열이 3개인 형태가 되도록 변경해주세요

```python
before : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]

=> after : [[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]]
```

In [11]:
# 우선 실행해주세요
arr = np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

In [12]:
answer4 = arr.reshape((5,3))

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [13]:
from numpy.testing import assert_array_equal

assert 'answer4' in globals(), "결과를 answer4라는 변수에 담아주세요!, answer4의 값을 보고 평가합니다."

A = [[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]

assert_array_equal(A, answer4,"\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!

> 문제 5번, 문제 6번은 table-2을 참고하여 풀어주세요!

#### table-2) 재수학원 학생들의 모의고사 성적표(월/학생)

|월/학생| 1 | 2 | 3 | 4 | 5 |6|7|8|9|
|---|----|---|---|---|---|---|---|---|---|
|A|390|382|393|362|375|392|358|367|396|
|B|300|297|311|320|336|340|342|357|360|
|C|187|190|167|164|163|171|178|151|180|
|D|298|267|254|302|300|308|380|384|392|
|E|96|78|390|80|72|396|68|92|400|

## 문제 5. 행렬의 shape 변경하기(2)

* 수능을 대비하여 학생들에게 3개월마다의 성적의 평균을 저장하고 있는 표를 만들어주세요

정답 >>>
```python

np.array([[388.33333333, 376.33333333, 373.66666667],
       [302.66666667, 332.        , 353.        ],
       [181.33333333, 166.        , 169.66666667],
       [273.        , 303.33333333, 385.33333333],
       [188.        , 182.66666667, 186.66666667]])
```

* 참고 : numpy에서의 평균

numpy에서 축별로 평균을 구하는 방법은 다음과 같습니다.

`numpy_array.mean(axis=n)`

예시 >
```python
A = np.array([1,3,5,7,9])
A.mean(axis=0) # 결과 >> 5.0
```

In [14]:
# 우선 실행해주세요
scores = np.array([
    [390,382,393,362,375,392,358,367,396],
    [300,297,311,320,336,340,342,357,360],
    [187,190,167,164,163,171,178,151,180],
    [298,267,254,302,300,308,380,384,392],
    [96,78,390,80,72,396,68,92,400]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer5`에 담아주세요

In [15]:
sorted_scores = scores.reshape(5,3,3)
answer5 = sorted_scores.mean(axis=2)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [16]:
from numpy.testing import assert_array_almost_equal

assert 'answer5' in globals(), "결과를 answer5라는 변수에 담아주세요!, answer5의 값을 보고 평가합니다."

A = np.array([[388.33333333, 376.33333333, 373.66666667],
       [302.66666667, 332.        , 353.        ],
       [181.33333333, 166.        , 169.66666667],
       [273.        , 303.33333333, 385.33333333],
       [188.        , 182.66666667, 186.66666667]])

assert_array_almost_equal(A,answer5,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

## 문제 6. 행렬의 shape 변경하기(3)

* table-2의 표는 현재 가로축에 `월`, 세로축에 `학생`이라는 정보를 담고 있습니다. 이 표를 가로축에 `학생`, 세로축에 `월`정보를 담도록 table-3과 같이 바꿔주세요

#### table-3) 재수학원 학생들의 모의고사 성적표(학생/월)

|학생/월| A | B | C | D | E |
|---|----|---|---|---|---|
|1|390|300|187|298|96|
|2|382|297|190|267|78|
|3|393|311|167|254|390|
|4|362|320|164|302|80|
|5|375|336|163|300|72|
|6|392|340|171|308|396|
|7|358|342|178|380|68|
|8|367|357|151|384|92|
|9|396|360|180|392|400|

* 변경 과정
![Imgur](https://i.imgur.com/iCP4Hs1l.png)

정답 >>>
```python

np.array([[390, 300, 187, 298,  96],
       [382, 297, 190, 267,  78],
       [393, 311, 167, 254, 390],
       [362, 320, 164, 302,  80],
       [375, 336, 163, 300,  72],
       [392, 340, 171, 308, 396],
       [358, 342, 178, 380,  68],
       [367, 357, 151, 384,  92],
       [396, 360, 180, 392, 400]])
```

In [17]:
# 우선 실행해주세요
scores = np.array([
    [390,382,393,362,375,392,358,367,396],
    [300,297,311,320,336,340,342,357,360],
    [187,190,167,164,163,171,178,151,180],
    [298,267,254,302,300,308,380,384,392],
    [96,78,390,80,72,396,68,92,400]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer6`에 담아주세요

In [18]:
answer6 = scores.transpose(1,0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [19]:
from numpy.testing import assert_array_almost_equal

assert 'answer6' in globals(), "결과를 answer6이라는 변수에 담아주세요!, answer6의 값을 보고 평가합니다."

A = np.array([[390, 300, 187, 298,  96],
       [382, 297, 190, 267,  78],
       [393, 311, 167, 254, 390],
       [362, 320, 164, 302,  80],
       [375, 336, 163, 300,  72],
       [392, 340, 171, 308, 396],
       [358, 342, 178, 380,  68],
       [367, 357, 151, 384,  92],
       [396, 360, 180, 392, 400]])

assert_array_almost_equal(A,answer6,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

> 문제 7번은 table-4를 참고하여 풀어주세요!

#### table-4) 재수학원 학생들의 월별 각 과목 성적표

* 3월 모의고사 성적표

|3월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|100|93|100|100|
|B|63|100|48|100|
|C|82|17|32|36|
|D|71|68|57|58|
|E|100|100|100|90|

* 6월 모의고사 성적표

|6월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|98|96|100|98|
|B|77|100|63|100|
|C|70|24|35|39|
|D|86|81|70|71|
|E|100|100|100|96|

* 9월 모의고사 성적표

|9월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|100|100|100|96|
|B|87|100|73|100|
|C|91|21|31|33|
|D|100|100|96|96|
|E|100|100|100|100|

## 문제 7. 행렬의 shape 변경하기(3)

* 3월, 6월, 9월 모의고사는 국가에서 실시하는 중요한 모의고사입니다. 중요한 시험이니만큼 3월, 6월, 9월 모의고사 성적은 table-4에 과목별로 정리를 했습니다. table-4의 표를 과목을 첫번째 기준으로 만든 표인 table-5의 표로 바꿔주세요

#### table-5) 과목별 학생들의 성적표

* 국어 성적표

|국어| 3월 | 6월 | 9월 |
|---|----|---|---|
|A|100|98|100|
|B|63|77|87|
|C|82|70|91|
|D|71|86|100|
|E|100|100|100|

* 수학 성적표

|수학| 3월 | 6월 | 9월 |
|---|----|---|---|
|A|93|96|100|
|B|100|100|100|
|C|17|24|21|
|D|68|81|100|
|E|100|100|100|

* 영어 성적표

|영어| 3월 | 6월 | 9월 |
|---|----|---|---|
|A|100|100|100|
|B|48|63|73|
|C|32|35|31|
|D|57|70|96|
|E|100|100|100|

* 과학 성적표

|과학| 3월 | 6월 | 9월 |
|---|----|---|---|
|A|100|98|96|
|B|100|100|100|
|C|36|39|33|
|D|58|71|96|
|E|90|96|100|

* 변경 과정

![Imgur](https://i.imgur.com/HdV8aQd.png)

정답 >>> 
```python
np.array([[[100,  98, 100],
        [ 63,  77,  87],
        [ 82,  70,  91],
        [ 71,  86, 100],
        [100, 100, 100]],

       [[ 93,  96, 100],
        [100, 100, 100],
        [ 17,  24,  21],
        [ 68,  81, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [ 48,  63,  73],
        [ 32,  35,  31],
        [ 57,  70,  96],
        [100, 100, 100]],

       [[100,  98,  96],
        [100, 100, 100],
        [ 36,  39,  33],
        [ 58,  71,  96],
        [ 90,  96, 100]]])
```

In [20]:
# 우선 입력해주세요
march_score = np.array([
    [100, 93, 100, 100],
    [63, 100, 48, 100],
    [82, 17, 32, 36],
    [71, 68, 57, 58],
    [100, 100, 100, 90]
])

june_score = np.array([
    [98, 96, 100, 98],
    [77, 100, 63, 100],
    [70, 24, 35, 39],
    [86, 81, 70, 71],
    [100, 100, 100, 96],
])

september_score = np.array([
    [100, 100, 100, 96],
    [87, 100, 73, 100],
    [91, 21, 31, 33],
    [100, 100, 96, 96],
    [100, 100, 100, 100]
])

important_score = np.stack((march_score, june_score, september_score))
important_score

array([[[100,  93, 100, 100],
        [ 63, 100,  48, 100],
        [ 82,  17,  32,  36],
        [ 71,  68,  57,  58],
        [100, 100, 100,  90]],

       [[ 98,  96, 100,  98],
        [ 77, 100,  63, 100],
        [ 70,  24,  35,  39],
        [ 86,  81,  70,  71],
        [100, 100, 100,  96]],

       [[100, 100, 100,  96],
        [ 87, 100,  73, 100],
        [ 91,  21,  31,  33],
        [100, 100,  96,  96],
        [100, 100, 100, 100]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer7`에 담아주세요

In [21]:
answer7 = important_score.transpose(2,1,0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [22]:
from numpy.testing import assert_array_almost_equal

assert 'answer7' in globals(), "결과를 answer7이라는 변수에 담아주세요!, answer7의 값을 보고 평가합니다."

A = np.array([[[100,  98, 100],
        [ 63,  77,  87],
        [ 82,  70,  91],
        [ 71,  86, 100],
        [100, 100, 100]],

       [[ 93,  96, 100],
        [100, 100, 100],
        [ 17,  24,  21],
        [ 68,  81, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [ 48,  63,  73],
        [ 32,  35,  31],
        [ 57,  70,  96],
        [100, 100, 100]],

       [[100,  98,  96],
        [100, 100, 100],
        [ 36,  39,  33],
        [ 58,  71,  96],
        [ 90,  96, 100]]])

assert_array_almost_equal(A,answer7,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

> 문제 8번, 문제 9번은 table-6을 참고하여 풀어주세요!

#### table-6) 2012년~2017년 삼성전자 분기별 매출

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 |

## 문제 8. np.concatenate를 사용해 data 추가하기(1)

* 위의 표에 다음과 같은 2018년 데이터를 추가한 표를 만들어주세요

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2018년 | 60.56 | 58.48 | 65.46 | 59.27 |

정답 >>>
```python
np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])
```

In [23]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer8`에 담아주세요

In [24]:
new_data = np.array([60.56, 58.48, 65.46, 59.27])
new_data = new_data.reshape(1,4)
new_sales = np.concatenate((sales, new_data), axis=0)
answer8 = new_sales

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [25]:
from numpy.testing import assert_array_almost_equal

assert 'answer8' in globals(), "결과를 answer8이라는 변수에 담아주세요!, answer8의 값을 보고 평가합니다."

A = np.array([[45.27, 47.6 , 52.18, 56.06],
       [52.87, 57.46, 59.08, 59.28],
       [53.68, 52.35, 47.45, 52.73],
       [47.12, 48.54, 51.68, 53.32],
       [49.78, 50.94, 47.82, 53.33],
       [50.55, 61.99, 62.05, 65.98],
       [60.56, 58.48, 65.46, 59.27]])

assert_array_almost_equal(A,answer8,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

## 문제 9. np.concatenate를 사용해 data 추가하기(2)

* 아래의 표와 같이 위의 표에 연도별 매출의 총합을 추가한 표를 만들어주세요

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 | 매출
| ------ | ----- | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 | 201.11 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 | 228.69 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 | 206.21 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 | 200.66 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 | 201.87 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 | 240.57 |

* 변경과정

![Imgur](https://i.imgur.com/Ep1WhZrl.png)

정답 >>>
```python
np.array([[ 45.27,  47.6 ,  52.18,  56.06, 201.11],
       [ 52.87,  57.46,  59.08,  59.28, 228.69],
       [ 53.68,  52.35,  47.45,  52.73, 206.21],
       [ 47.12,  48.54,  51.68,  53.32, 200.66],
       [ 49.78,  50.94,  47.82,  53.33, 201.87],
       [ 50.55,  61.99,  62.05,  65.98, 240.57]])
```

In [26]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer9`에 담아주세요

In [27]:
sum_data = sales.sum(axis=1)
sum_data = sum_data.reshape(6,1)
answer9 = np.concatenate((sales, sum_data), axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [28]:
from numpy.testing import assert_array_almost_equal

assert 'answer9' in globals(), "결과를 answer9라는 변수에 담아주세요!, answer9의 값을 보고 평가합니다."

A = np.array([[ 45.27,  47.6 ,  52.18,  56.06, 201.11],
       [ 52.87,  57.46,  59.08,  59.28, 228.69],
       [ 53.68,  52.35,  47.45,  52.73, 206.21],
       [ 47.12,  48.54,  51.68,  53.32, 200.66],
       [ 49.78,  50.94,  47.82,  53.33, 201.87],
       [ 50.55,  61.99,  62.05,  65.98, 240.57]])

assert_array_almost_equal(A,answer9,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

> 문제 10번, 문제 11번, 문제 12번, 문제 13번은 table-7을 참고하여 풀어주세요!

#### table-7) 득점순위에 따른 리그별 축구선수들의 데이터

* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

## 문제 10 np.stack(1)

* 위의 표는 각 리그의 축구 선수들의 데이터들을 나타낸 것입니다. 문제 10번에서는 3개의 표를 np.stack을 이용해 table-8과 같은 표로 나타내주세요 


* 힌트 : **축과 shape**에 집중해주세요

#### table-8) 데이터별로 각 리그들을 비교하며 득점순위 순서대로 보고싶을 때

* 득점순위 1등들의 데이터

|득점1등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|22|1|87|42|36|
|스페인|36|13|171|88|34|
|이탈리아|26|8|119|70|37|

* 득점순위 2등들의 데이터

|득점2등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|22|5|93|40|36|
|스페인|21|6|111|58|33|
|이탈리아|23|7|92|58|37|

* 득점순위 3등들의 데이터

|득점3등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|22|8|135|64|38|
|스페인|21|6|104|45|36|
|이탈리아|22|0|91|60|37|

* 득점순위 4등들의 데이터

|득점4등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|21|8|117|43|33|
|스페인|20|6|70|31|27|
|이탈리아|21|6|136|77|31|

* 득점순위 5등들의 데이터

|득점5등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|16|15|94|43|37|
|스페인|19|0|80|40|32|
|이탈리아|17|3|92|59|35|

* 득점순위 6등들의 데이터

|득점6등|골|도움|슈팅|유효슈팅|경기수|
|---|---|---|---|---|---|
|영국|12|6|74|29|31|
|스페인|15|8|112|46|37|
|이탈리아|16|9|76|45|35|

<br><br>

* 변경 과정

![Imgur](https://i.imgur.com/FVXMVtc.png)

정답 > 
```python
np.array([[[ 22,   1,  87,  42,  36],
        [ 36,  13, 171,  88,  34],
        [ 26,   8, 119,  70,  37]],

       [[ 22,   5,  93,  40,  36],
        [ 21,   6, 111,  58,  33],
        [ 23,   7,  92,  58,  37]],

       [[ 22,   8, 135,  64,  38],
        [ 21,   6, 104,  45,  36],
        [ 22,   0,  91,  60,  37]],

       [[ 21,   8, 117,  43,  33],
        [ 20,   6,  70,  31,  27],
        [ 21,   6, 136,  77,  31]],

       [[ 16,  15,  94,  43,  37],
        [ 19,   0,  80,  40,  32],
        [ 17,   3,  92,  59,  35]],

       [[ 12,   6,  74,  29,  31],
        [ 15,   8, 112,  46,  37],
        [ 16,   9,  76,  45,  35]]])
```

In [29]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer10`에 담아주세요

In [30]:
answer10 = np.stack((england, spain, italy), axis=1)
# 득점 순위끼리의 데이터 > [1등[영국[골,도움,슈팅,유효슈팅,도움], 스페인[골,도움,슈팅,유효슈팅,도움], 이탈리아[...]...], 2등[[...]]...]
#(6,3,5)
# 득점순위들의 데이터를 교차하여 보고 싶을 때
# 데이터별로 각각의 국가들을 비교하며 득점순위 순서대로 보고싶을 때

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [31]:
from numpy.testing import assert_array_almost_equal

assert 'answer10' in globals(), "결과를 answer10이라는 변수에 담아주세요!, answer10의 값을 보고 평가합니다."

A = np.array([[[ 22,   1,  87,  42,  36],
        [ 36,  13, 171,  88,  34],
        [ 26,   8, 119,  70,  37]],

       [[ 22,   5,  93,  40,  36],
        [ 21,   6, 111,  58,  33],
        [ 23,   7,  92,  58,  37]],

       [[ 22,   8, 135,  64,  38],
        [ 21,   6, 104,  45,  36],
        [ 22,   0,  91,  60,  37]],

       [[ 21,   8, 117,  43,  33],
        [ 20,   6,  70,  31,  27],
        [ 21,   6, 136,  77,  31]],

       [[ 16,  15,  94,  43,  37],
        [ 19,   0,  80,  40,  32],
        [ 17,   3,  92,  59,  35]],

       [[ 12,   6,  74,  29,  31],
        [ 15,   8, 112,  46,  37],
        [ 16,   9,  76,  45,  35]]])

assert_array_almost_equal(A,answer10,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

## 문제 11. np.stack(2)

* 문제 11번에서는 3개의 표를 np.stack을 이용해 table-9와 같은 표로 나타내주세요 


* 힌트 : **축과 shape**에 집중해주세요

#### table-9) 리그별로 각각의 데이터들을 비교하며 득점순위 순서대로 보고싶을 때

* 득점순위 1등들의 리그기준 데이터

|득점1등|영국|스페인|이탈리아|
|---|---|---|---|
|골|22|36|26|
|도움|1|13|8|
|슈팅|87|171|119|
|유효슈팅|42|88|70|
|경기수|36|34|37|

* 득점순위 2등들의 리그기준 데이터

|득점2등|영국|스페인|이탈리아|
|---|---|---|---|
|골|22|21|23|
|도움|5|6|7|
|슈팅|93|111|92|
|유효슈팅|40|58|58|
|경기수|36|33|37|

* 득점순위 3등들의 리그기준 데이터

|득점3등|영국|스페인|이탈리아|
|---|---|---|---|
|골|22|21|22|
|도움|8|6|0|
|슈팅|135|104|91|
|유효슈팅|64|45|60|
|경기수|38|36|37|

* 득점순위 4등들의 리그기준 데이터

|득점4등|영국|스페인|이탈리아|
|---|---|---|---|
|골|21|20|21|
|도움|8|6|6|
|슈팅|117|70|136|
|유효슈팅|43|31|77|
|경기수|33|27|31|

* 득점순위 5등들의 리그기준 데이터

|득점5등|영국|스페인|이탈리아|
|---|---|---|---|
|골|16|19|17|
|도움|15|0|3|
|슈팅|94|80|92|
|유효슈팅|43|40|59|
|경기수|37|32|35|

* 득점순위 6등들의 리그기준 데이터

|득점6등|영국|스페인|이탈리아|
|---|---|---|---|
|골|12|15|16|
|도움|6|8|9|
|슈팅|74|112|76|
|유효슈팅|29|46|45|
|경기수|31|37|35|

<br><br>

* 변경 과정

![Imgur](https://i.imgur.com/uGXzvxj.png)


정답 > 
```python
np.array([[[ 22,  36,  26],
        [  1,  13,   8],
        [ 87, 171, 119],
        [ 42,  88,  70],
        [ 36,  34,  37]],

       [[ 22,  21,  23],
        [  5,   6,   7],
        [ 93, 111,  92],
        [ 40,  58,  58],
        [ 36,  33,  37]],

       [[ 22,  21,  22],
        [  8,   6,   0],
        [135, 104,  91],
        [ 64,  45,  60],
        [ 38,  36,  37]],

       [[ 21,  20,  21],
        [  8,   6,   6],
        [117,  70, 136],
        [ 43,  31,  77],
        [ 33,  27,  31]],

       [[ 16,  19,  17],
        [ 15,   0,   3],
        [ 94,  80,  92],
        [ 43,  40,  59],
        [ 37,  32,  35]],

       [[ 12,  15,  16],
        [  6,   8,   9],
        [ 74, 112,  76],
        [ 29,  46,  45],
        [ 31,  37,  35]]])
```

In [32]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer11`에 담아주세요

In [33]:
answer11 = np.stack((england, spain, italy), axis=2)
# 데이터에 따라 > [1등[골[영국, 스페인, 이탈리아], 도움[영국, 스페인, 이탈리아], 슈팅[...]...], 2등[[...]]]
#(6,5,3)
# 데이터들을 중심적으로 보고싶을 때
# 국가별로 각각의 데이터들을 비교하며 득점순위 순서대로 보고싶을 때

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [34]:
from numpy.testing import assert_array_almost_equal

assert 'answer11' in globals(), "결과를 answer11이라는 변수에 담아주세요!, answer11의 값을 보고 평가합니다."

A = np.array([[[ 22,  36,  26],
        [  1,  13,   8],
        [ 87, 171, 119],
        [ 42,  88,  70],
        [ 36,  34,  37]],

       [[ 22,  21,  23],
        [  5,   6,   7],
        [ 93, 111,  92],
        [ 40,  58,  58],
        [ 36,  33,  37]],

       [[ 22,  21,  22],
        [  8,   6,   0],
        [135, 104,  91],
        [ 64,  45,  60],
        [ 38,  36,  37]],

       [[ 21,  20,  21],
        [  8,   6,   6],
        [117,  70, 136],
        [ 43,  31,  77],
        [ 33,  27,  31]],

       [[ 16,  19,  17],
        [ 15,   0,   3],
        [ 94,  80,  92],
        [ 43,  40,  59],
        [ 37,  32,  35]],

       [[ 12,  15,  16],
        [  6,   8,   9],
        [ 74, 112,  76],
        [ 29,  46,  45],
        [ 31,  37,  35]]])

assert_array_almost_equal(A,answer11,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

## 문제 12. np.stack(3)

* 문제 12번에서는 3개의 표를 np.stack을 이용해 table-10과 같은 표로 나타내주세요 


* 힌트 : **축과 shape**에 집중해주세요

#### table-10) 데이터별로 선수의 득점순위를 비교하며 국가순서대로 보고싶을 때

* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

정답 > 
```python
np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])
```

In [35]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer12`에 담아주세요

In [36]:
answer12 = np.stack((england, spain, italy), axis=0)
# 국가끼리의 데이터 > [영국[1등[골,도움,슈팅,유효슈팅,도움], 2등[골,도움,슈팅,유효슈팅,도움], 3등[...]...], 스페인[[...]]...]
# (3,6,5)
# 데이터별로 선수의 득점순위를 비교하며 국가순서대로 보고싶을 때

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [37]:
from numpy.testing import assert_array_almost_equal

assert 'answer12' in globals(), "결과를 answer12라는 변수에 담아주세요!, answer12의 값을 보고 평가합니다."

A = np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

assert_array_almost_equal(A,answer12,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

## 문제 13. 새로운 데이터 추가하기

* 문제 12에 있는 테이블에 각 리그 7등들의 데이터를 추가해주세요  


* 힌트 : **축과 shape**에 집중해주세요


* 영국리그 7등들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국7등 |11 |13 |78 | 38 | 38 |

* 스페인리그 7등들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인7등 |15 |2 |121 | 57 | 38 |

* 이탈리아리그 7등들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아7등 |16 |4 |82 | 58 | 38 |

<br><br>

* 변경 과정 

![Imgur](https://i.imgur.com/UGKpbDX.png)

정답 > 
```python
np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31],
        [ 11,  13,  78,  38,  38]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37],
        [ 16,   4,  82,  58,  38]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35],
        [ 15,   2, 121,  57,  38]]])
```

In [38]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer13`에 담아주세요

In [39]:
player_list = np.stack((england, spain, italy), axis=0)

seventh_england = np.array([11,13,78,38,38])
seventh_spain = np.array([15,2,121,57,38])
seventh_italy = np.array([16,4,82,58,38])

seventh_player = np.stack((seventh_england, seventh_italy, seventh_spain))
seventh_player = seventh_player.reshape(3,1,5)

answer13 = np.concatenate([player_list, seventh_player],axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [40]:
from numpy.testing import assert_array_almost_equal

assert 'answer13' in globals(), "결과를 answer13이라는 변수에 담아주세요!, answer13의 값을 보고 평가합니다."

A = np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31],
        [ 11,  13,  78,  38,  38]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37],
        [ 16,   4,  82,  58,  38]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35],
        [ 15,   2, 121,  57,  38]]])
assert_array_almost_equal(A,answer13,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!

#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, DoYeong Kim ( ka2k@publicai.co.kr )  last updated on 2019/07/12
</div>
<hr>